### PR TITLE
Fix maximum call stack error when using cloneDeep in query transformer #45

### PR DESCRIPTION
**Pull request by dimitri-koenig**
Fix maximum call stack error when using cloneDeep in query transformer #45

### CODE REVIEW

**Comment by dimitri-koenig** [comment]
Any status updates on merging this PR?

**Comment by chriszarate** [comment]
Affecting us as well, would be great to get this merged or otherwise addressed.

**Comment by Poincare** [comment]
This solution feels like a "hack" to me but I'm open to merging it with a small TODO above it since it does seem to solve the problem. I'll go ahead and do that + release.

**Comment by dimitri-koenig** [comment]
Thx. I know it's kinda hacky. If you have a better solution feel free to provide.

**Pull request merged**
